--
-- AUTOGENERATED BY MATUGEN, DO NOT EDIT --
--
require("base16-colorscheme").setup({
	base00 = "#18130b", -- bg
	base01 = "#18130b", -- completion menu bg
	base02 = "#9d8f7b",
	base03 = "#9d8f7b", -- comments
	base04 = "#d5c4af",
	base05 = "#ece1d3", -- variables
	base06 = "#362f27",
	base07 = "#3f382f",
	base08 = "#a1cdff", -- variables, modules
	base09 = "#ffb4ab", -- numbers, enum values
	base0A = "#ffb4ab", -- classes
	base0B = "#a1cdff", -- text
	base0C = "#69b3fc",
	base0D = "#e1a32c", -- functions
	base0E = "#ffdeac", -- errors, rust keywords
	base0F = "#a1cdff",
})
