--
-- AUTOGENERATED BY MATUGEN, DO NOT EDIT --
--

local M = {}

M.reset_colors = function()
	require("base16-colorscheme").setup({
		base00 = "#18130b", -- bg
		base01 = "#18130b", -- completion menu bg
		base02 = "#9d8f7b",
		base03 = "#9d8f7b", -- comments
		base04 = "#d5c4af",
		base05 = "#ece1d3", -- parameters
		base06 = "#362f27",
		base07 = "#3f382f",
		base08 = "#ece1d3", -- variables, modules
		base09 = "#ffb4ab", -- numbers, enum values
		base0A = "#a1cdff", -- classes
		base0B = "#a1cdff", -- text
		base0C = "#69b3fc",
		base0D = "#e1a32c", -- functions
		base0E = "#e5c18a", -- errors, rust keywords
		base0F = "#a1cdff",
	})

	local function update_hl(name, changes)
		local old_hl = vim.api.nvim_get_hl(0, { name = name, link = false })
		local new_hl = vim.tbl_deep_extend("force", old_hl, changes)
		vim.api.nvim_set_hl(0, name, new_hl)
	end

	-- other theme customizations
	update_hl("TSFunction", { italic = true })
	update_hl("TSVariableBuiltin", { fg = "#ffb4ab" })
	update_hl("TSVariableBuiltin", { fg = "#ffb4ab" })
	update_hl("GitSignsAdd", { fg = "#69b3fc" })
	update_hl("GitSignsChange", { fg = "#e1a32c" })
	update_hl("GitSignsDelete", { fg = "#93000a" })
end

return M
