# -----------------------------------------------------
# Example Hyprland config file - to split into modules
# -----------------------------------------------------
source = ~/.config/hypr/conf/example.conf

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = ~/.config/hypr/conf/autostart.conf
