#
# Symlink this to ~/.zshrc if no using Nix Home Manager
#
# Prefer zsh shell in terminal
zsh_bin=$(which zsh)
[[ -n "$zsh_bin" ]] && SHELL=$zsh_bin
unset zsh_bin

autoload -U compinit && compinit

# Source manually installed plugins
#   git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh_plug/
#   git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.zsh_plug/
zsh_plugs=~/.zsh_plugs
for plug in zsh-autosuggestions zsh-syntax-highlighting; do
    [[ -e "$zsh_plugs/$plug/$plug.plugin.zsh" ]] && echo $plug && source $zsh_plugs/$plug/$plug.plugin.zsh
done
unset zsh_plugs

# Configure autosuggestions: use most recent history match
ZSH_AUTOSUGGEST_STRATEGY=(history)

# Install fzf bindings
command -v fzf >/dev/null 2>&1 && source <(fzf --zsh)

# Load the common config
source ~/.config/zsh/conf/main.zsh

# Powerlevel10k installed manually (Home Manager sources its Nix package directly).
source ~/.config/zsh/conf/p10k.zsh
[[ ! -r ~/.zsh_plugs/powerlevel10k/powerlevel10k.zsh-theme ]] || \
    source ~/.zsh_plugs/powerlevel10k/powerlevel10k.zsh-theme
