#!/bin/bash

set -e

SCRIPT_DIR=$(cd "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# update nix
sudo -i nix-channel --update
# sudo -i nix-env --install --attr nixpkgs.nix nixpkgs.cacert
sudo -i systemctl daemon-reload
sudo -i systemctl restart nix-daemon

# update home-manager packages
home-manager switch --impure

# show home-manager package diff
"$SCRIPT_DIR/home-manager-diff-last"
